name: release

on: [pull_request]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: configure python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: install
        run: |
          sudo apt-get install -y graphviz
          pip install git+https://github.com/cylc/cylc-flow/  # install latest cylc-flow
          pip install -e .[all]
      - name: build
        run: |
          make html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.FOO }}
          publish_dir: ./_build/html
          publish_branch: gh-pages
